__title__ = 'i3ipc'
__description__ = 'An improved Python library to control i3wm and sway'
__url__ = 'https://github.com/acrisci/i3ipc-python'
__version__ = '1.7.1'
__author__ = 'Tony Crisci'
__author_email__ = 'tony@dubstepdish.com'
__license__ = 'BSD-3-Clause'
__copyright__ = 'Copyright 2015 Tony Crisci'
